import java.io.*;
import java.util.HashMap;
import java.util.Scanner;
import java.util.Vector;

public class SearchMap {

    /**
     *
     * @param FileName
     * @param nodes
     * @param allDestinations
     * @return
     */
    public static String ReadAndParseFile(String FileName, HashMap<String, Vertex> nodes, Vector<String> allDestinations){
        StringBuilder sb = new StringBuilder();
        String origin = "";
        try {
            Scanner sc = new Scanner(new File(FileName));

            origin = sc.nextLine();
            nodes.put(origin,new Vertex(origin));

            while(sc.hasNextLine()){
                String curr = sc.nextLine();
                String[] data = curr.split(" "  );

                String currOrigin = data[0];
                String currDestination = data[1];
                double currAmount = Double.parseDouble(data[2]);

                if(!allDestinations.contains(currOrigin) && !currOrigin.equalsIgnoreCase(origin)){
                    allDestinations.add(currOrigin);
                }

                if(!allDestinations.contains(currDestination) && !currDestination.equalsIgnoreCase(origin)){
                    allDestinations.add(currDestination);
                }

                if(nodes.containsKey(currOrigin)){
                    Vertex currVertex = nodes.get(currOrigin);
                    currVertex.getEdges().put(
                            currDestination,
                            currAmount
                    );

                }else{
                    Vertex currVertex = new Vertex(currOrigin);

                    currVertex.getEdges().put(
                            currDestination,
                            currAmount
                    );
                    nodes.put(currOrigin,currVertex);
                }


                if(!nodes.containsKey(currDestination)){
                    Vertex currVertex = new Vertex(currDestination);
                    nodes.put(currDestination,currVertex);
                }
            }
            sc.close();
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        return origin;
    }

    /**
     * Takes the Data and the output filename and writes it to that file, if outputile does not
     * exsits then creates one.
     * @param Filename : The output filename, recieved as a CLI argument from user at start
     * @param data : The data to be written to the output file provided which are the routes generated by FlightMap
     *
     */
    public static void WriteToFile(String Filename, String data){

        BufferedWriter writer = null;
        try {
            writer = new BufferedWriter(new FileWriter(Filename));
            writer.write(data);
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     *
     * @param args
     */
    public static void main(String [] args){
        String inputFile = "";
        String outputFile = "";

        HashMap<String,Vertex> map = new HashMap<>();
        Vector<String> allDestinations = new Vector<>();
        if(args.length !=2){
            System.out.println("Error: Please enter correct command line inputs");
            System.exit(0);
        }
        inputFile = args[0];
        outputFile = args[1];

        String origin = ReadAndParseFile(inputFile,map,allDestinations);
        FlightMap fm = new FlightMap();
        String data = fm.findFlights(map,origin,allDestinations);
        WriteToFile(outputFile,data);

    }




}
